name: CI/CD Pipeline

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GHCR_TOKEN }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: pull images
      run: docker compose pull

    - name: setup container
      run: docker compose up -d --wait