name: run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.GHCR_TOKEN }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: pull images
      run: docker compose pull
      
    - name: setup container
      run: sudo docker compose up --no-build --wait

    - name: install project
      run: |
        sudo docker exec -u 0 hub composer install
        sudo docker exec -u 0 hub composer setup

    - name: setup database
      run: sudo docker exec -u 0 hub composer testing

    - name: add permissions to phpunit executable
      run: sudo docker exec -u 0 hub chmod 777 vendor/bin/phpunit
        
    - name: Execute tests - PHPUnit
      run: sudo docker exec -u 0 hub vendor/bin/phpunit